-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v0.9.1
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: autopep8-wrapper
        args:
        - -i
        - --ignore=E265,E309,E501
    -   id: debug-statements
        exclude: examples/*
    # -   id: flake8
    #     exclude: examples/*
    -   id: check-yaml
    -   id: check-json
    -   id: check-merge-conflict
    -   id: name-tests-test
        exclude: tests/(common.py|util.py|(helpers)/(.+).py)
-   repo: git://github.com/asottile/reorder_python_imports
    rev: v0.3.5
    hooks:
    -   id: reorder-python-imports
        language_version: python2.7
        args:
        - --add-import
        - from __future__ import absolute_import
        - --add-import
        - from __future__ import unicode_literals
